export const MenuList=[
    {
        title:"FITNESS",
        url:"/fitness",
        cName:"nav-links"
    },
    {
        title:"CARE",
        url:"/care",
        cName:"nav-links"
    },
    {
        title:"MIND",
        url:"mind",
        cName:"nav-links"
    },
    {
        title:"STORE",
        url:"/store",
        cName:"nav-links"
    },
    {
        title:"CART",
        url:"/cart",
        cName:"nav-links-mobile"
    },
    {
        title:"SIGN-UP",
        url:"/sign",
        cName:"nav-links-mobile"
    },
]