export const MenuList=[
    {
        title:"FITNESS",
        url:"#f",
        cName:"nav-links"
    },
    {
        title:"CARE",
        url:"#ca",
        cName:"nav-links"
    },
    {
        title:"MIND",
        url:"#m",
        cName:"nav-links"
    },
    {
        title:"STORE",
        url:"#st",
        cName:"nav-links"
    },
    {
        title:"CART",
        url:"#c",
        cName:"nav-links-mobile"
    },
    {
        title:"SIGN-UP",
        url:"#s",
        cName:"nav-links-mobile"
    },
]